#!/bin/bash

if [ $EUID -ne 0 ];
then
 echo "Root required!"
 exit 1
fi

cd bin
echo '== enabling module... ==='
./magento module:enable Amazingcard_JsonApi
echo '=== upgrading... ==='
./magento setup:upgrade
echo '=== compiling...==='
./magento setup:di:compile
cd -
