#!/bin/bash

if [ ! -w ~/www/magento/var/generation ];
then
 echo "Crap... I have no write access to ~/www/magento/var/generation..."
 exit 1
fi

cd bin
echo '== enabling module... ==='
./magento module:enable Amazingcard_JsonApi
echo '=== upgrading... ==='
./magento setup:upgrade
echo '=== compiling...==='
./magento setup:di:compile
cd -
